export default [
    { name: 'Laravel', link: '#', logo: 'LaravelLogo.svg' },
    { name: 'React', link: '#', logo: 'ReactLogo.svg' },
    { name: 'Vue', link: '#', logo: 'VueLogo.svg' },
    { name: 'Nuxt', link: '#', logo: 'NuxtLogo.svg' },
    { name: 'Tailwind', link: '#', logo: 'TailwindLogo.svg' },
    { name: 'TablePlus', link: '#', logo: 'TablePlusLogo.svg' },
    { name: 'Visual Studio', link: '#', logo: 'VisualStudioLogo.svg' },
    { name: '.NET', link: '#', logo: 'DotNotLogo.svg' },
    { name: 'Teams', link: '#', logo: 'TeamsLogo.svg' },
    { name: 'C#', link: '#', logo: 'CSharpLogo.svg' },
    { name: 'MySQL', link: '#', logo: 'MySQLLogo.svg' },
    { name: 'MSSQL', link: '#', logo: 'MSSQLLogo.svg' },
    { name: 'DevOps', link: '#', logo: 'DevOpsLogo.svg' },
    { name: 'Azure', link: '#', logo: 'AzureLogo.svg' },
    { name: 'Digital Ocean', link: '#', logo: 'DigitalOceanLogo.svg' },
    { name: 'AWS', link: '#', logo: 'AWSLogo.svg' },
    { name: 'Mailgun', link: '#', logo: 'MailgunLogo.svg' },
    { name: 'Docker', link: '#', logo: 'DockerLogo.svg' },
    { name: 'Jira', link: '#', logo: 'JiraLogo.svg' },
    { name: 'ChatGPT', link: '#', logo: 'ChatGPTLogo.svg' },
    { name: 'Adobe', link: '#', logo: 'AdobeLogo.svg' },
    { name: 'Figma', link: '#', logo: 'FigmaLogo.svg' },
    { name: 'GitHub', link: '#', logo: 'GitHubLogo.svg' },
    { name: 'Vite', link: '#', logo: 'ViteLogo.svg' },
    { name: 'Web3', link: '#', logo: 'EthereumLogo.svg' },
]
