export default [
    {
        name: 'Laravel',
        link: 'https://laravel.com',
        darkLogoUrl: 'laravel-dark.png',
        lightLogoUrl: 'laravel-light.png',
    },
    {
        name: 'React',
        link: 'https://react.com',
        darkLogoUrl: 'react-dark.png',
        lightLogoUrl: 'react-light.png',
    },
    {
        name: 'Vue',
        link: 'https://vue.com',
        darkLogoUrl: 'vue-dark.png',
        lightLogoUrl: 'vue-light.png',
    },
    {
        name: 'Nuxt',
        link: 'https://nuxt.com',
        darkLogoUrl: 'nuxt-dark.png',
        lightLogoUrl: 'nuxt-light.png',
    },
    {
        name: 'Next',
        link: 'https://nextjs.org',
        darkLogoUrl: 'next-dark.png',
        lightLogoUrl: 'next-light.png',
    },
    {
        name: 'Vercel',
        link: 'https://vercel.com',
        darkLogoUrl: 'vercel-dark.png',
        lightLogoUrl: 'vercel-light.png',
    },
    {
        name: 'Tailwind',
        link: 'https://tailwindcss.com',
        darkLogoUrl: 'tailwind-dark.png',
        lightLogoUrl: 'tailwind-light.png',
    },
    {
        name: 'TablePlus',
        link: 'https://tablueplus.com',
        darkLogoUrl: 'tableplus-dark.png',
        lightLogoUrl: 'tableplus-light.png',
    },
    {
        name: 'Visual Studio',
        link: 'https://visualstudio.microsoft.com',
        darkLogoUrl: 'visualstudio-dark.png',
        lightLogoUrl: 'visualstudio-light.png',
    },
    {
        name: '.NET',
        link: 'https://dotnet.microsoft.com',
        darkLogoUrl: 'dotnet-dark.png',
        lightLogoUrl: 'dotnet-light.png',
    },
    {
        name: 'Teams',
        link: 'https://www.microsoft.com/en-us/microsoft-teams/group-chat-software',
        darkLogoUrl: 'teams-dark.png',
        lightLogoUrl: 'teams-light.png',
    },
    {
        name: 'C#',
        link: 'https://learn.microsoft.com/en-us/dotnet/csharp',
        darkLogoUrl: 'csharp-dark.png',
        lightLogoUrl: 'csharp-light.png',
    },
    {
        name: 'MySQL',
        link: 'https://mysql.com',
        darkLogoUrl: 'mysql-dark.png',
        lightLogoUrl: 'mysql-light.png',
    },
    {
        name: 'MSSQL',
        link: 'https://azure.microsoft.com/en-gb/products/azure-sql/database',
        darkLogoUrl: 'mssql-dark.png',
        lightLogoUrl: 'mssql-light.png',
    },
    {
        name: 'DevOps',
        link: 'https://azure.microsoft.com/en-us/products/devops',
        darkLogoUrl: 'devops-dark.png',
        lightLogoUrl: 'devops-light.png',
    },
    {
        name: 'Azure',
        link: 'https://azure.microsoft.com/',
        darkLogoUrl: 'azure-dark.png',
        lightLogoUrl: 'azure-light.png',
    },
    {
        name: 'Digital Ocean',
        link: 'https://digitalocean.com',
        darkLogoUrl: 'digitalocean-dark.png',
        lightLogoUrl: 'digitalocean-light.png',
    },
    {
        name: 'AWS',
        link: 'https://aws.amazon.com',
        darkLogoUrl: 'aws-dark.png',
        lightLogoUrl: 'aws-light.png',
    },
    {
        name: 'Mailgun',
        link: 'https://mailgun.com',
        darkLogoUrl: 'mailgun-dark.png',
        lightLogoUrl: 'mailgun-dark.png',
    },
    {
        name: 'Docker',
        link: 'https://docker.com',
        darkLogoUrl: 'docker-dark.png',
        lightLogoUrl: 'docker-light.png',
    },
    {
        name: 'Jira',
        link: 'https://www.atlassian.com/software/jira',
        darkLogoUrl: 'jira-dark.png',
        lightLogoUrl: 'jira-light.png',
    },
    {
        name: 'ChatGPT',
        link: 'https://chat.openai.com',
        darkLogoUrl: 'chatgpt-dark.png',
        lightLogoUrl: 'chatgpt-light.png',
    },
    {
        name: 'Adobe',
        link: 'https://www.adobe.com',
        darkLogoUrl: 'adobe-dark.png',
        lightLogoUrl: 'adobe-light.png',
    },
    {
        name: 'Figma',
        link: 'https://figma.com',
        darkLogoUrl: 'figma-dark.png',
        lightLogoUrl: 'figma-light.png',
    },
    {
        name: 'GitHub',
        link: 'https://github.com',
        darkLogoUrl: 'github-dark.png',
        lightLogoUrl: 'github-light.png',
    },
    {
        name: 'Vite',
        link: 'https://vitejs.dev',
        darkLogoUrl: 'vite-dark.png',
        lightLogoUrl: 'vite-light.png',
    },
    {
        name: 'Forge',
        link: 'https://forge.laravel.com',
        darkLogoUrl: 'forge-dark.png',
        lightLogoUrl: 'forge-light.png',
    },
    {
        name: 'Trello',
        link: 'https://trello.com',
        darkLogoUrl: 'trello-dark.png',
        lightLogoUrl: 'trello-light.png',
    },
    {
        name: 'Solidity',
        link: null,
        darkLogoUrl: 'solidity-dark.png',
        lightLogoUrl: 'solidity-light.png',
    },
    {
        name: 'Typescript',
        link: null,
        darkLogoUrl: 'typescript-dark.png',
        lightLogoUrl: 'typescript-light.png',
    },
    {
        name: 'Sentry',
        link: null,
        darkLogoUrl: 'sentry-dark.png',
        lightLogoUrl: 'sentry-light.png',
    },
    {
        name: 'Remix',
        link: 'https://remix.run',
        darkLogoUrl: 'remix-dark.png',
        lightLogoUrl: 'remix-light.png',
    },
]
