export default [
    { name: 'Laravel', link: 'https://laravel.com', logoUrl: 'laravel.png' },
    { name: 'React', link: 'https://react.com', logoUrl: 'react.png' },
    { name: 'Vue', link: 'https://vue.com', logoUrl: 'vue.png' },
    { name: 'Nuxt', link: 'https://nuxt.com', logoUrl: 'nuxt.png' },
    { name: 'Next', link: 'https://nextjs.org', logoUrl: 'next.png' },
    { name: 'Vercel', link: 'https://vercel.com', logoUrl: 'vercel.png' },
    {
        name: 'Tailwind',
        link: 'https://tailwindcss.com',
        logoUrl: 'tailwind.png',
    },
    {
        name: 'TablePlus',
        link: 'https://tablueplus.com',
        logoUrl: 'table-plus.png',
    },
    {
        name: 'Visual Studio',
        link: 'https://visualstudio.microsoft.com',
        logoUrl: 'visualstudio.png',
    },
    {
        name: '.NET',
        link: 'https://dotnet.microsoft.com',
        logoUrl: 'dotnet.png',
    },
    {
        name: 'Teams',
        link: 'https://www.microsoft.com/en-us/microsoft-teams/group-chat-software',
        logoUrl: 'teams.png',
    },
    {
        name: 'C#',
        link: 'https://learn.microsoft.com/en-us/dotnet/csharp',
        logoUrl: 'csharp.png',
    },
    { name: 'MySQL', link: 'https://mysql.com', logoUrl: 'mysql.png' },
    {
        name: 'MSSQL',
        link: 'https://azure.microsoft.com/en-gb/products/azure-sql/database',
        logoUrl: 'mssql.png',
    },
    {
        name: 'DevOps',
        link: 'https://azure.microsoft.com/en-us/products/devops',
        logoUrl: 'devops.png',
    },
    {
        name: 'Azure',
        link: 'https://azure.microsoft.com/',
        logoUrl: 'azure.png',
    },
    {
        name: 'Digital Ocean',
        link: 'https://digitalocean.com',
        logoUrl: 'digitalocean.png',
    },
    { name: 'AWS', link: 'https://aws.amazon.com', logoUrl: 'aws.png' },
    { name: 'Mailgun', link: 'https://mailgun.com', logoUrl: 'mailgun.png' },
    { name: 'Docker', link: 'https://docker.com', logoUrl: 'docker.png' },
    {
        name: 'Jira',
        link: 'https://www.atlassian.com/software/jira',
        logoUrl: 'jira.png',
    },
    {
        name: 'ChatGPT',
        link: 'https://chat.openai.com',
        logoUrl: 'chatgpt.png',
    },
    { name: 'Adobe', link: 'https://www.adobe.com', logoUrl: 'adobe.png' },
    { name: 'Figma', link: 'https://figma.com', logoUrl: 'figma.png' },
    { name: 'GitHub', link: 'https://github.com', logoUrl: 'github.png' },
    { name: 'Vite', link: 'https://vitejs.dev', logoUrl: 'vite.png' },
    { name: 'Web3', link: null, logoUrl: 'eth.png' },
    { name: 'Forge', link: 'https://forge.laravel.com', logoUrl: 'forge.png' },
    { name: 'Trello', link: 'https://trello.com', logoUrl: 'trello.png' },
    { name: 'Solidity', link: null, logoUrl: 'solidity.png' },
    { name: 'Typescript', link: null, logoUrl: 'typescript.png' },
    { name: 'Sentry', link: null, logoUrl: 'sentry.png' },
]
