export default [
    { name: 'Laravel', link: 'https://laravel.com', logo: 'laravel.png' },
    { name: 'React', link: 'https://react.com', logo: 'react.png' },
    { name: 'Vue', link: 'https://vue.com', logo: 'vue.png' },
    { name: 'Nuxt', link: 'https://nuxt.com', logo: 'nuxt.png' },
    { name: 'Next', link: 'https://nextjs.org', logo: 'next.png' },
    { name: 'Vercel', link: 'https://vercel.com', logo: 'vercel.png' },
    { name: 'Tailwind', link: 'https://tailwindcss.com', logo: 'tailwind.png' },
    {
        name: 'TablePlus',
        link: 'https://tablueplus.com',
        logo: 'table-plus.png',
    },
    {
        name: 'Visual Studio',
        link: 'https://visualstudio.microsoft.com',
        logo: 'visstudio.png',
    },
    { name: '.NET', link: 'https://dotnet.microsoft.com', logo: 'net.png' },
    {
        name: 'Teams',
        link: 'https://www.microsoft.com/en-us/microsoft-teams/group-chat-software',
        logo: 'teams.png',
    },
    {
        name: 'C#',
        link: 'https://learn.microsoft.com/en-us/dotnet/csharp',
        logo: 'c.png',
    },
    { name: 'MySQL', link: 'https://mysql.com', logo: 'mysql.png' },
    {
        name: 'MSSQL',
        link: 'https://azure.microsoft.com/en-gb/products/azure-sql/database',
        logo: 'mssql.png',
    },
    {
        name: 'DevOps',
        link: 'https://azure.microsoft.com/en-us/products/devops',
        logo: 'devops.png',
    },
    { name: 'Azure', link: 'https://azure.microsoft.com/', logo: 'azure.png' },
    {
        name: 'Digital Ocean',
        link: 'https://digitalocean.com',
        logo: 'digital-ocean.png',
    },
    { name: 'AWS', link: 'https://aws.amazon.com', logo: 'aws.png' },
    { name: 'Mailgun', link: 'https://mailgun.com', logo: 'mailgun.png' },
    { name: 'Docker', link: 'https://docker.com', logo: 'docker.png' },
    {
        name: 'Jira',
        link: 'https://www.atlassian.com/software/jira',
        logo: 'jira.png',
    },
    { name: 'ChatGPT', link: 'https://chat.openai.com', logo: 'chatgpt.png' },
    { name: 'Adobe', link: 'https://www.adobe.com', logo: 'adobe.png' },
    { name: 'Figma', link: 'https://figma.com', logo: 'figma.png' },
    { name: 'GitHub', link: 'https://github.com', logo: 'github.png' },
    { name: 'Vite', link: 'https://vitejs.dev', logo: 'vite.png' },
    { name: 'Web3', logo: 'eth.png' },
    { name: 'Forge', link: 'https://forge.laravel.com', logo: 'forge.png' },
    { name: 'Trello', link: 'https://trello.com', logo: 'trello.png' },
]
