import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import Footer from '@/components/Footer'
import { Locale } from '@/utils/enums/locale'
import LocaleContextProvider from '@/components/LocaleContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export async function generateStaticParams() {
    return [
        { lang: Locale.Chinese },
        { lang: Locale.English },
        { lang: Locale.German },
        { lang: Locale.Spanish },
    ]
}

export default function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode
    params: { lang: Locale }
}>) {
    return (
        <html lang={params.lang}>
            <body className={inter.className}>
                <LocaleContextProvider locale={params.lang}>
                    <header></header>

                    <main>{children}</main>

                    <Footer />
                </LocaleContextProvider>
            </body>
        </html>
    )
}
